### ISSUE TITLE
突发情况，不能使用，应该检查哪里？

### ISSUE THREAD

**Issue by zxhyc131** [yyss8/webpack-bundle-cdn-uploader#1]
```⠹ building for production... 文件已上传: static/css/app.fdb269ab9041f05f9a23be031931360d.css
⠏ building for production...events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:342:17)
    at TLSSocket.socketOnEnd (_http_client.js:443:23)
    at TLSSocket.emit (events.js:201:15)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
Emitted 'error' event at:
    at TLSSocket.socketOnEnd (_http_client.js:443:9)
    at TLSSocket.emit (events.js:201:15)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
前一天可以用   隔天就不行了   配置中间没改过。

**Comment by zxhyc131** [comment]
嗯  经过重新安装依赖   又好了，不过还是不清楚具体出问题的原因。
